name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Make bash script executable
        run: chmod +x script.sh

      - name: Run a script that showed your last and first name
        run: ./script.sh
